"""
services/groq_ai.py — Generates PR descriptions from git diffs using Groq.

Groq's free tier: 14,400 requests/day on llama-3.3-70b-versatile.
At typical PR sizes that's plenty for an early-stage product.
"""

import httpx
from config import get_settings

# Max characters of diff to send — avoids blowing the context window.
# llama-3.3-70b has 128k tokens; 12k chars ≈ ~3k tokens, leaving room for output.
MAX_DIFF_CHARS = 12_000


SYSTEM_PROMPT = """You are an expert software engineer writing GitHub pull request descriptions.
Given a git diff, write a clear, structured PR description in Markdown.

Your output must follow this exact format:

## What changed
[1–3 sentences summarising the changes at a high level]

## Why
[1–2 sentences on the motivation or problem being solved — infer from code if not obvious]

## How
[Bullet points of the key implementation details — what was added, removed, or refactored]

## Testing
[Brief note on what was tested or how to verify — infer from test files in the diff if present]

Rules:
- Be specific and technical, not vague
- Do NOT start with "This PR" — it's redundant
- Infer context from file names, function names, and code patterns
- If the diff is tiny (e.g. a single line fix), keep each section to 1 sentence
- Use plain language, no jargon for jargon's sake
- Never fabricate test assertions or specific numbers you can't see in the diff
"""


async def generate_pr_description(
    diff: str,
    pr_title: str,
    repo_name: str,
    base_branch: str,
) -> str:
    """
    Call Groq and return a Markdown PR description string.
    Raises httpx.HTTPStatusError on API failure.
    """
    settings = get_settings()

    # Trim diff if it's huge
    truncated = False
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS]
        truncated = True

    user_message = f"""Repository: {repo_name}
PR title: {pr_title}
Base branch: {base_branch}

Git diff:
```diff
{diff}
```
{"[Note: diff was truncated to fit context window]" if truncated else ""}

Write the PR description now."""

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.groq_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.groq_model,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_message},
                ],
                "max_tokens": 800,
                "temperature": 0.3,  # Low temp = consistent, professional output
            },
        )
        response.raise_for_status()

    data = response.json()
    description = data["choices"][0]["message"]["content"].strip()

    # Append a small footer so users know it was AI-generated (good practice)
    footer = "\n\n---\n*Description generated by [PR Describer](https://pr-describer.com) · [Edit]()*"
    return description + footer
